### PR TITLE
App update for improved user experience

### PR DESCRIPTION
**Pull request by driehle**
This PR provides a new version of the Indico check-in app. Besides upates for many libraries this PR mostly adds new features for an improved user experience. First of all, the registrations of an event are cached locally. Therefore, tapping on an event with about 1.000 registrations now displays the registrants immediatly (given they are in cache already) while silently updated them in the background (with a loading indicator shown). The list of registrants can now be filtered by name for easily looking up participants. As the current app hangs for a significant time as soon as there are more than 250 attendees, this PR adds an infinite scroll feature, were the list is rendered as the user scrolls down. This significantly increases the user experience.

Second, the view for individual registrations has been updated. Here, the attendee's name is also display from cache (if available), while the current information are loaded from the server. This removes the "lag" which otherwise occured after selecting an attendee from the list or after scanning a QR ticket. The scanning of QR codes has been fastened as well, by removing the display time or the scanned result. Here, a button for turning on the phone's light (torch) has been added as well to support scanning of printed tickets under low light conditions.

Lastly, a feature called auto check-in has been added. When enabled, the attendee is automatically marked as checked in as soon as their QR code is scanned (and validated). This eliminates the manual tapping on the check-in button and, hence, drastically increases the check-in procedure. This feature is optional and not enabled by default. When auto check-in is enabled and a ticket of a person that is already checked in is scanned, a warning is displayed.

An APK file is attached for your convenience: [app-debug.zip](https://github.com/indico/indico-checkin/files/3173251/app-debug.zip). This PR has only been tested on Android 7 and Android 8. I will not be able to test it on different platforms.

Changes:
 - updated AngularJS from 1.2.14 to 1.7.8
 - added jQuery 3.4.1
 - added ngInfiniteScroll 1.0.0
 - added spin.js 4.0.0
 - updated cordova-android to 8.0.0
 - updated controllers to work with AngularJS 1.8
 - added settings page
 - added auto check-in feature
 - made QR-code scanning faster (no result display, only QR-code)
 - added local cache for registrants
 - added search function / filtering for registrant list
 - added loading indicators
 - app version increased to 1.5.0, APK version 421

### CODE REVIEW

**Comment by driehle** [comment]
Is the Indico checkin app still maintained?

**Comment by pferreir** [comment]
@driehle sorry for the delay. Yes, it's still maintained, mostly for bug fixes.

Thanks a lot for this PR, it's really appreciated. At the same time, it would be great if next time we could discuss this before the development. We were thinking of moving the whole app to react-native at some point, in which case the "enhanced UI" would come "for free". Of course you work is already quite an improvement and we're very thankful for it, but if we had discussed the developments beforehand, maybe we would have found a way to collaborate in something even better.

**Comment by driehle** [comment]
@pferreir Considering the overall progress of the indico mobile app over the last two years, which is considerably low, I am wondering why this PR does not get merged. If this would have been merged two years ago, I think there would have been a great benefit for all users. Sorry to bother, but not merging small contributions that improve the as-is state in favour of targeting a whole rewrite of the app (React, Vue.js, etc.) seems like a questionable stategy to me.

**Comment by pferreir** [comment]
@driehle thanks for the feedback. I believe this kind of fell through the cracks with the work in 3.0, which is obviously our fault. Apologies for that.
We certainly didn't mean to refuse the contribution, my point was that we could have joined forces in something better (which we still want to provide, BTW), and this is why it's always nice to ping us whenever you are thinking of contributing something substantial.

But that aside, I propose we work on merging it as of next week.

**Comment by liangjun-jiang** [comment]
now I hope @driehle  could fix those conflicts and have this PR merged in very soon.

**Comment by pferreir** [comment]
> now I hope @driehle could fix those conflicts and have this PR merged in very soon.

We'll have a look, no worries.

**Comment by driehle** [comment]
I'll close this in favour of #16, which is based on this PR.

**Pull request closed without merging**
